### ISSUE TITLE
GitLab - "Start timer" button missing after latest UI update

### ISSUE THREAD

**Issue by breadadams** [toggl/toggl-button#886]
### Environment details

* Operation system: Mac (Chrome)
* Extension version: 1.6.0

### Expected behavior
Should see a "start timer" in the issue/merge-request/etc header. Like this (from prev. version):
![image](https://user-images.githubusercontent.com/5795227/30521216-93f8f46a-9bbc-11e7-96be-1cf3de8632fc.png)

### Actual behavior
No toggl button 😢 
![image](https://user-images.githubusercontent.com/5795227/30521222-bca0e27e-9bbc-11e7-90cf-ed21bbd01386.png)

### Steps to reproduce the behavior
Just visit GitLab - the new UI has been made public it seems - so _everyone_ should see it.

### Additional details
A temporary work around would be to deactivate GitLab's new UI, as you could previously, but it seems it's been fully rolled out

**Comment by breadadams** [comment]
Hmm but this **was** fixed in 1.6.0 (https://github.com/toggl/toggl-button/pull/885)? 🤔

**Comment by emilv** [comment]
1.6.0 is not released in all channels yet. The last version Toggl chose to release to Mozilla Addons is 1.5.0.

**Comment by jdalrymple** [comment]
Same problem with chrome (arch linux)

**Comment by breadadams** [comment]
I see `1.6.0` in Chrome @emilv ❓ 🤔 . Or have I misunderstood something? 

![image](https://user-images.githubusercontent.com/5795227/30543078-09f8f7f8-9c82-11e7-9ed4-5fffbbe24d66.png)

**Comment by emilv** [comment]
Ah, so you are saying that you are running 1.6.0, which *should* be fixed, but it still does not work for you! I apparently skipped that detail in your report and just assumed everyone was using Firefox...

**Comment by breadadams** [comment]
No problem @emilv :v:. Yeah that's exactly it, I mentioned the browser in _Environment details -> Operation system_.

**Comment by syko** [comment]
Hi,
You're correct, 1.6.0 fixed a gitlab issue but gitlab changed again and this was once again fixed by #885 but this just hasn't been released yet.

So this has actually been fixed and we can close this issue. I will do another release shortly.

Also, note that Mozilla has a pretty lengthy review process so the release cycle for the firefox version is much slower.

**Comment by MikeSorokin** [comment]
@syko This update broke integration for older GitLab version (9.5.1) for both old and new themes. Button appears in html code, but is not visible for human beings :)

**Comment by syko** [comment]
goddamn. I guess there is no way to easily test this using the online version of gitlab :/

**Comment by MikeSorokin** [comment]
@syko yeah, just the last update. I think, we could do this way: fix this thing for latest version and allow users to define in integration options specific styles/classes for their needs

**Comment by syko** [comment]
> fix this thing for latest version and allow users to define in integration options specific styles/classes for their needs.

That would be too complex. Choosing between gitlab version is also an option but there is no reason why we couldn't support both. We just need to make the content script adapt to the 2 DOM options. The tricky part is the testing.

**Comment by scrobbleme** [comment]
Same here. Not working since a couple of weeks.

**Comment by LulzAugusto** [comment]
Hey @scrobbleme, are you also on version (9.5.1)?

**Comment by scrobbleme** [comment]
@LulzAugusto Yes, latest.

**Comment by breadadams** [comment]
It appears to be back! 🎉 

![image](https://user-images.githubusercontent.com/5795227/30881994-f345efa2-a307-11e7-8998-cd2dca39c625.png)

**Comment by MikeSorokin** [comment]
@breadadams what is your GitLab version? On 9.5.1 button still is invisible, as there are no released updates in this extension.

**Comment by syko** [comment]
Might possibly be fixed with the next release

**Comment by MikeSorokin** [comment]
@syko GitLab 9.5.1 btn release 1.8.0 - it works again! Thanks a lot! :+1:
